config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :posts do
    resources :likes
  end

  get 'posts/index'

  get 'user_posts/:user_id' => 'posts#user', as: :user_posts

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :likes
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :likes
  def handle
    self.email.split('@') [0]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
       post = Post.find( params[:post_id] )

       if like = Like.find_by( post: post, user: current_user )
          like.destroy
       else
          like = Like.new( post: post, user: current_user )
          like.save
       end

       redirect_to posts_path
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def create
    post_params = params.require( :post ).permit( :content )

    @post = Post.new( content: post_params[:content] )
    @post.user = current_user

    if @post.save
      redirect_to posts_path
    else
      render posts_path
    end
  end

  def index
    @posts = Post.order( created_at: :desc)
  end

  def user
    @user = User.find( params[:user_id] )
    @posts = Post.where( user: @user ).order( created_at: :desc )
    @likes = @user.likes.joins( :post ).order( "posts.created_at DESC" )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <%= link_to "Postal", '/', class: "navbar-brand" %>
    <nav>
      <ul class="nav navbar-nav">
        <li><%= link_to "Posts", posts_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if !user_signed_in? %>
          <li><%= link_to "Log In", new_user_session_path %></li>
        <% else %>
          <li><span class="navbar-text"><%= current_user.email %></span></li>
          <li><%= link_to "Log Out", destroy_user_session_path, :method => :delete %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Postal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/header" %>

<main class="container">
  <%= yield %>
</main>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for Post.new do |f| %>
  <div class="input-group col-xs-12">
    <div class="col-xs-8"><%= f.text_field :content, class: "form-control" %></div>
    <div class="col-xs-4"><%= f.submit "Create", class: "btn" %></div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="col-xs-8">
   <p>
      <h4><%= post.content %></h4>

      <% liked = Like.find_by( post: post, user: current_user ) != nil %>
      <% btn_color = liked ? "warning" : "default" %>

      <%= link_to "ツ", post_likes_path( post ), method: :post, class: "btn btn-#{btn_color} btn-xs", disabled: !user_signed_in? %>
      <%= post.likes.count %>

      &nbsp

      <em><%= link_to post.user.handle, user_posts_path( post.user ) %></em>
   </p>
</div>

app/views/posts/index.html.erb
<% if user_signed_in? %>
  <%= render "form" %>
  <br>
<% end %>

<%= render @posts %>

app/views/posts/user.html.erb
<h1><%= @user.handle %></h1>

<br>

<% @posts.each do |post| %>
   <h4><%= post.content %></h4>
<% end %>
<br>

<h1>likes</h1>
<br>

<% @likes.each do |like| %>
  <% if like.post.user_id != @user.id %>
    <h4><%= like.post.content %></h4>
  <% end %>
<% end %>